#!/bin/sh

addgroup -g ${RRSYNC_GID} rrsync
adduser -u ${RRSYNC_UID} -G rrsync -D rrsync
passwd -u rrsync

mkdir /tmp/rrsync
chown rrsync:rrsync /archives /tmp/rrsync

cd /home/rrsync
su rrsync -s /bin/sh /usr/local/bin/rrsync-wrapper-init

# Start SSH daemon
cd /
echo "Starting SSH daemon..."
exec /usr/sbin/sshd -D
